config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "buyers#index"
  get "comprador/:id" => "buyers#show", as: :buyer
  get "precios" => "prices#index"
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_many_attached :certifications

  has_many :requirements
  has_many :material_relations
  has_many :materials, through: :material_relations

  has_one :country, class_name: "Buyer", foreign_key: 'buyer_id'
  #has_many :buyers, class_name: "Buyer", foreign_key: 'buyer_id'

  has_many :prices

  enum :semaphore, [
    'Verde',
    'Amarillo',
    'Rojo'
  ]
  enum :btype, [
    'País',
    'Compradores finales',
    'Intermediario',
    'Emprendedores'
  ]
  enum :market, [
    'Local',
    'Nacional',
    'Exporta'
  ]

  def self.ransackable_attributes(auth_object = nil)
    ["address", "btype", "coordinates", "country_id", "created_at", "description", "id", "name", "semaphore", "updated_at", "email", "website", "phone", "market", "anual_volume", "mensual_volume" ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["buyer"]
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  def show
    @buyer = Buyer.find(params[:id])
  end

  def index
    @expand = false
    @country_options = []
    @materials_options = Material.all.map {|m| [m.name, m.id]}
    @buyer_options = []
    req_company = {}
    req_country = {}
    @semaphore = []
    @countries = []
    buyers = Buyer
    if params[:buyers].present?
      buy = params[:buyers].split(',')
      buyers = buyers.where(id: buy)
      #paises salen de compradores
    end
    if params[:countries].present?
      ctries = params[:countries].split(',')
      buyers = buyers.where(buyer_id: ctries)
    end
    if params[:materials].present?
      mats = params[:materials].split(',')
      buyers = buyers.includes(:materials).where('materials.id': mats)
    end
    if params[:semaphore].present?
      sems = params[:semaphore].split(',')
      buyers = buyers.where(semaphore: sems)
    end

    #TODO filtros por separado de requisitos
    #if params[:buyers].present?
    #  buyers = buyers.where(params[:buyers])
    #end
    Buyer.where( id: buyers.pluck(:buyer_id).uniq ).each do |c|
      creq = c.requirements
      country = {
        id: c.id,
        name: c.name,
        materials: c.materials.count,
        requirements: creq.count,
        semaphore: c.semaphore,
        coordinates: c.coordinates,
        buyers: [],
        buyers_requirements: 0
      }
      creq.each do |cr|
        if req_country[cr.id].nil?
          req_country[cr.id] = [cr.name, cr.id]
        end
      end
      breq = 0
      buyers.where(buyer_id: c.id).each do |b|
        buyer = {
          id: b.id,
          name: b.name,
          materials: b.materials.count == 1 ? b.materials.first.name : b.materials.count,
          semaphore: b.semaphore,
          coordinates: b.coordinates,
          btype: b.btype,
          requirements: []
        }
        @buyer_options.push [b.name, b.id]
        b.requirements.each do |r|
          breq += 1
          req_company[r.requirement_category.id] = [r.requirement_category.name, r.requirement_category.id]
          req = {
            material: r.material.name,
            category: r.requirement_category.name,
            semaphore: r.semaphore,
          }
          buyer[:requirements].push( req )
        end
        country[:buyers].push(buyer)
      end
      country[:buyers_requirements] = breq
      @countries.push(country)
      logger.debug "\n\nCOUNTRIES\n#{@countries.inspect}\n\n"
      @country_options.push( [c.name,c.id] )
    end
    @req_country = req_country.values
    @req_company = req_company.values
    respond_to do |format|
      format.html
      format.turbo_stream {
        @expand = true
      }
    end
  end
  #
  #

end

app/helpers/buyers_helper.rb
module BuyersHelper
  def semaphore(color)
    "<div class='semaphore'>
      <span class='circle big red #{color != 'Rojo' ? 'fade' : ''}'></span>
      <span class='circle big yellow #{color != 'Amarillo' ? 'fade' : ''}'></span>
      <span class='circle big green #{color != 'Verde' ? 'fade' : ''}'></span>
    </div>".html_safe
  end
end

app/views/buyers/_filters.html.erb
<div id="filters" data-controller='filters'>
  <div class="select-filter">
    <i class="fa fa-flag"></i>
    <%= select_tag :countries, options_for_select(@country_options), { data: { action: 'filters#search', 'filters-target': 'countries' }, multiple: true } %>
  </div>
  <div class="select-filter">
    <i class="fa fa-recycle"></i>
    <%= select_tag :materials, options_for_select(@materials_options), { data: { action: 'filters#search', 'filters-target': 'materials' }, multiple: true } %>
  </div>
  <div class="select-filter">
    <i class="fa fa-industry-windows"></i>
    <%= select_tag :buyers, options_for_select(@buyer_options), { data: { action: 'filters#search', 'filters-target': 'buyers' }, multiple: true } %>
  </div>
  <div class="select-filter">
    <i class="fa fa-clipboard-list-check"></i>
    <%= select_tag :req_company, options_for_select(@req_company), { data: { action: 'filters#search', 'filters-target': 'req_company' }, multiple: true } %>
  </div>
  <div class="select-filter">
    <i class="fa fa-building-columns"></i>
    <%= select_tag :req_country, options_for_select(@req_country), { data: { action: 'filters#search', 'filters-target': 'req_country' }, multiple: true } %>
  </div>
  <div class="select-filter">
    <i class="fa fa-traffic-light"></i>
    <%= select_tag :semaphore, options_for_select(['Verde', 'Amarillo', 'Rojo']), { data: { action: 'filters#search', 'filters-target': 'semaphore' }, multiple: true } %>
  </div>
</div>

app/views/buyers/_table.html.erb
<table id="buyers">
  <tr class="theaders">
    <th><i class="fa fa-flag"></i>País</th>
    <th><i class="fa fa-recycle"></i>Materiales</th>
    <th><i class="fa fa-industry-windows"></i>Compradores</th>
    <th><i class="fa fa-clipboard-list-check"></i>Req. Empresa</th>
    <th><i class="fa fa-building-columns"></i>Req. País</th>
    <th><i class="fa fa-traffic-light"></i>Semáforo</th>
    <th></th>
  </tr>
  <% @countries.each do |c| %>
  <tr class="country" data-controller="buyers" data-buyers-target="buyer" data-buyers-id-value=<%= c[:id] %>>
    <td class="name"><%= link_to c[:name], buyer_path(c[:id]), target: '_blank' %></td>
    <td class="materials"><%= c[:materials] %></td>
    <td class="bcont"><%= c[:buyers].count %></td>
    <td class="breq"><%= c[:buyers_requirements] %></td>
    <td class="req"><%= c[:requirements] %></td>
    <td class="semaphore-wraper"><%= semaphore(c[:semaphore]) %></td>
    <td class="action"><button data-action='buyers#expand'>Ver compradores ></button></td>
  </tr>
    <% c[:buyers].each do |b| %>
      <tr class="buyers child-<%= c[:id] %>" data-controller="buyers" data-buyers-target="buyer" data-buyers-id-value=<%= b[:id] %>>
        <td class="name"><%= link_to b[:name], buyer_path(b[:id]), target: '_blank' %></td>
        <td class="materials"><%= b[:materials] %></td>
        <td class="btype"><%= b[:btype] %></td>
        <td class="breq"><%= b[:requirements].count %></td>
        <td class="creq"><%= c[:requirements] %></td>
        <td class="semaphore-wraper"><%= semaphore(b[:semaphore]) %></td>
        <td class="action">
          <%= b[:requirements].length > 0 ? "<button data-action='buyers#expand'>Ver requerimientos ></button>".html_safe : '' %>
        </td>
      </tr>
      <% if b[:coordinates].present? %>
      <% coords = b[:coordinates].split(',') %>
        <script>
          window.markers.push({
            coords: [<%= coords[0].strip.to_d %>, <%= coords[1].strip.to_d %>],
            name: '<%= "#{b[:name]} (#{b[:btype]})" %>'
          })
        </script>
      <% end %>
      <% b[:requirements].each do |r| %>
        <tr class="requirements child-<%= b[:id] %>">
          <td class=""></td>
          <td class="materials"><%= r[:material] %></td>
          <td class=""></td>
          <td class="rcat"><%= r[:category] %></td>
          <td class=""></td>
          <td class="semaphore-wraper"><%= semaphore(r[:semaphore]) %></td>
          <td class=""></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>  
</table>
<% if @expand %>
  <div data-controller="listener" data-listener-action-value='expand'></div>
<% end %>

app/views/buyers/index.html.erb
<script>window.markers = []</script>
<div class="home">
  <div class="header">
    <h1>Compradores</h1>
  </div>
  <div id="content">
    <%= render partial: 'filters' %>
    <div class="section">
    <%= turbo_frame_tag "buyers_table" do %>
        <%= render partial: 'table' %>
    <% end %>
    </div>
    <div class="section" data-controller="map"> 
      <div id="map" style="height: 700px"></div>  
    </div>
  </div>
</div>

app/views/buyers/index.turbo_stream.erb
<%= turbo_stream.update("buyers_table") do %>
  <script>window.markers = []</script>
  <%= render partial: 'table' %>
<% end %>

app/views/buyers/show.html.erb
<div class="header">
  <h1>Ficha de <%= @buyer.name %></h1>
</div>
<div id="content" class="buyer">
  <div class="info">
    <div class="info-left">
      <div class="info-title">
        <h2><%= @buyer.name %></h2>
        <span>(<%= @buyer.btype %>)</span>
      </div>
      <div class="semaphore-wraper"><%= semaphore(@buyer.semaphore) %></div>
      <div class="materials"><b>Materiales: </b><%= @buyer.materials.pluck(:name).join(', ') %></div>
      <% if @buyer.btype != 'País' %>
      <ul>
        <li><i class="fa fa-location-dot"></i><span><%= @buyer.address %></span></li>
        <li><i class="fa fa-phone"></i><span><%= @buyer.phone %></span></li>
        <li><i class="fa fa-at"></i><span><%= @buyer.email %></span></li>
        <li><i class="fa fa-globe"></i><span><%= @buyer.website %></span></li>
      </ul>
      <% end %>
    </div>
    <% if @buyer.coordinates.present? %>
      <% coords = @buyer.coordinates.split(',') %>
      <script>window.markers=[{coords: [<%= coords[0] %>, <%= coords[1] %>], name: '<%= @buyer.name %>'}]</script>
    <% else %>
      <script>window.markers=[]</script>
    <% end %>
    <div class="info-right" data-controller="map">
      <div id="map" style="height: 400px"></div>
    </div>
  </div>
  <div class="section country-requirements">
    <%
      if @buyer.btype == 'País'
        country = @buyer
      else
        country = Buyer.find(@buyer.buyer_id)
      end
    %>
    <table id="buyers">
      <tr class="theaders">
        <th><i class="fa fa-flag"></i>Requerimientos País</th>
        <th><i class="fa fa-recycle"></i>Material</th>
        <th><i class="fa fa-industry-windows"></i>Categoría</th>
        <th><i class="fa fa-traffic-light"></i>Semáforo</th>
      </tr>
      <% country.requirements.each do |r|%>
      <tr>
        <td class="name"><%= "<h4>#{r.name}</h4><p>#{r.description}</p>".html_safe %></td>
        <td class="materials"><%= r.material.name %></td>
        <td class="req"><%= r.requirement_category.name %></td>
        <td class="semaphore-wraper"><%= semaphore(r.semaphore) %></td>
      </tr>
      <% end %>
    </table>
    <% if @buyer.btype != 'País' %>
      <table id="buyers-reqs">
        <tr class="theaders">
          <th><i class="fa fa-flag"></i>Requerimientos Empresa</th>
          <th><i class="fa fa-recycle"></i>Material</th>
          <th><i class="fa fa-industry-windows"></i>Categoría</th>
          <th><i class="fa fa-traffic-light"></i>Semáforo</th>
        </tr>
        <% @buyer.requirements.each do |r|%>
        <tr>
          <td class="name"><%= "<h4>#{r.name}</h4><p>#{r.description}</p>".html_safe %></td>
          <td class="materials"><%= r.material.name %></td>
          <td class="req"><%= r.requirement_category.name %></td>
          <td class="semaphore-wraper"><%= semaphore(r.semaphore) %></td>
        </tr>
      <% end %>
    </table>
    <% end %>
  </div>
</div>